/**
 * Node test script for the canonical draft hashing implementation.
 *
 * No test framework — plain `assert`. Checks that frontend/js/canonical.js
 * produces the same hashes as the vectors in contract/test_vectors.json
 * (which were generated by the Python reference implementation).
 *
 * Run: node frontend/js/canonical.test.js
 */

"use strict";

var assert = require("assert");
var path = require("path");
var fs = require("fs");

var canonical = require("./canonical.js");

// ── Load test vectors ──────────────────────────────────────────

var vectorsPath = path.resolve(__dirname, "..", "..", "contract", "test_vectors.json");
var vectorsData = JSON.parse(fs.readFileSync(vectorsPath, "utf-8"));
var vectors = vectorsData.vectors;

var passed = 0;
var failed = 0;

function ok(msg) {
    passed++;
    console.log("  PASS: " + msg);
}

function fail(msg) {
    failed++;
    console.error("  FAIL: " + msg);
}

console.log("");
console.log("=== canonical.test.js — " + vectors.length + " vectors ===");
console.log("");

// ── Test each vector ────────────────────────────────────────────

vectors.forEach(function (vector, index) {
    var desc = "vector " + index + ": " + vector.description;

    if (vector.should_raise) {
        // This vector must raise an error.
        try {
            canonical.draftHash(vector.draft);
            fail(desc + " — expected error but none was raised");
        } catch (e) {
            // Only the canonicaliser's own rejections count; a TypeError
            // from a bug must not pass as "raised as expected".
            if (/forbidden in the canonical form/.test(e.message)) {
                ok(desc + " — raised as expected (" + e.message + ")");
            } else {
                fail(desc + " — raised the wrong error: " + e.message);
            }
        }
    } else {
        try {
            var actual = canonical.draftHash(vector.draft);
            var expected = vector.expected_hash;
            assert.strictEqual(
                actual,
                expected,
                desc + " — hash mismatch"
            );
            ok(desc + " — " + actual.substring(0, 16) + "...");
        } catch (e) {
            if (e instanceof assert.AssertionError) {
                fail(desc + " — " + e.message);
            } else {
                fail(desc + " — unexpected error: " + e.message);
            }
        }
    }
});

// ── Key-order independence ─────────────────────────────────────

(function () {
    var h0 = canonical.draftHash(vectors[0].draft);
    var h1 = canonical.draftHash(vectors[1].draft);
    var h2 = canonical.draftHash(vectors[2].draft);
    try {
        assert.strictEqual(h0, h1, "key order independence (v0 vs v1)");
        assert.strictEqual(h0, h2, "key order independence (v0 vs v2)");
        ok("key-order independence: v0 == v1 == v2");
    } catch (e) {
        fail(e.message);
    }
})();

// ── Excluded fields do not affect hash ─────────────────────────

(function () {
    var hWithout = canonical.draftHash(vectors[0].draft);
    var hWith = canonical.draftHash(vectors[5].draft);
    try {
        assert.strictEqual(hWithout, hWith, "excluded fields affect hash");
        ok("excluded fields (signature, confidence) do not affect hash");
    } catch (e) {
        fail(e.message);
    }
})();

// ── One-char change produces different hash ────────────────────

(function () {
    var hOriginal = canonical.draftHash(vectors[0].draft);
    var hChanged = canonical.draftHash(vectors[7].draft);
    try {
        assert.notStrictEqual(hOriginal, hChanged, "one-char change did not change hash");
        ok("one-character change produces a different hash");
    } catch (e) {
        fail(e.message);
    }
})();

// ── Array order matters ────────────────────────────────────────

(function () {
    var h1 = canonical.draftHash(vectors[9].draft);
    var h2 = canonical.draftHash(vectors[10].draft);
    try {
        assert.notStrictEqual(h1, h2, "array order did not matter");
        ok("array element order affects hash");
    } catch (e) {
        fail(e.message);
    }
})();

// ── No whitespace between tokens in canonical bytes ────────────

(function () {
    var bytes = canonical.canonicalBytes(vectors[0].draft);
    var s = Buffer.from(bytes).toString("utf-8");
    // Spaces inside string values are fine; we only check for whitespace
    // that would appear as token separators (after { [ , : and before } ] ,).
    var structuralSpace = /[{\[,]\s|\s[}\],]|:\s|\s:/.test(s);
    try {
        assert.strictEqual(structuralSpace, false, "whitespace found between tokens");
        ok("no whitespace between tokens in canonical bytes");
    } catch (e) {
        fail(e.message);
    }
})();

// ── Key sort: code point, not UTF-16 code unit ─────────────────

// A deliberately wrong canonicaliser: identical except it uses the
// default .sort(), which orders keys by UTF-16 code units.
function naiveUtf16SortHash(draft) {
    function ser(v) {
        if (Array.isArray(v)) return "[" + v.map(ser).join(",") + "]";
        if (v !== null && typeof v === "object") {
            return "{" + Object.keys(v).sort().map(function (k) {
                return JSON.stringify(k) + ":" + ser(v[k]);
            }).join(",") + "}";
        }
        return JSON.stringify(v);
    }
    var root = {};
    Object.keys(draft).forEach(function (k) {
        if (canonical.EXCLUDED_FIELDS.indexOf(k) === -1) root[k] = draft[k];
    });
    return require("crypto").createHash("sha256").update(ser(root), "utf8").digest("hex");
}

(function () {
    var sortVector = vectors.filter(function (v) {
        return v.description.indexOf("key sort: U+FF5A vs emoji") === 0;
    })[0];
    try {
        assert.ok(sortVector, "key sort vector missing");
        // Control: on ASCII keys the naive version agrees.
        assert.strictEqual(naiveUtf16SortHash(vectors[0].draft), vectors[0].expected_hash,
            "naive sort should agree on ASCII-only keys");
        assert.deepStrictEqual(["ｚ", "😀"].sort(), ["😀", "ｚ"],
            "default .sort() should put the emoji first");
        assert.strictEqual(canonical.draftHash(sortVector.draft), sortVector.expected_hash,
            "code-point sort mismatch");
        assert.notStrictEqual(naiveUtf16SortHash(sortVector.draft), sortVector.expected_hash,
            "key sort vector does not catch a naive .sort()");
        ok("key sort vector catches a naive UTF-16 .sort() implementation");
    } catch (e) {
        fail(e.message);
    }
})();

// ── Malformed input is rejected ─────────────────────────────────

(function () {
    var bad = ["\ud800", "\udc00", "a\ud83d", "\ude00b"];
    try {
        bad.forEach(function (s) {
            var vObj = {}; vObj.v = s;
            var kObj = {}; kObj[s] = "v";
            assert.throws(function () { canonical.draftHash(vObj); }, /surrogate/, "value " + JSON.stringify(s));
            assert.throws(function () { canonical.draftHash(kObj); }, /surrogate/, "key " + JSON.stringify(s));
        });
        assert.throws(function () { canonical.draftHash({ v: null }); }, /null/);
        ok("lone surrogates and null are rejected");
    } catch (e) {
        fail(e.message);
    }
})();

(function () {
    var s = Buffer.from(canonical.canonicalBytes({ v: "\u0000\u001f\n" })).toString("utf-8");
    try {
        assert.strictEqual(s, '{"v":"\\u0000\\u001f\\n"}');
        ok("control characters use lowercase hex escapes");
    } catch (e) {
        fail(e.message);
    }
})();

// ── Determinism ────────────────────────────────────────────────

(function () {
    var b1 = canonical.canonicalBytes(vectors[0].draft);
    var b2 = canonical.canonicalBytes(vectors[0].draft);
    try {
        assert.deepStrictEqual(
            Array.from(b1),
            Array.from(b2),
            "canonical_bytes is not deterministic"
        );
        ok("canonical_bytes is deterministic");
    } catch (e) {
        fail(e.message);
    }
})();

// ── Summary ────────────────────────────────────────────────────

console.log("");
console.log("=== " + passed + " passed, " + failed + " failed ===");
console.log("");

if (failed > 0) {
    process.exit(1);
}
