/**
 * Node test script for the canonical draft hashing implementation.
 *
 * No test framework — plain `assert`. Checks that frontend/js/canonical.js
 * produces the same hashes as the vectors in contract/test_vectors.json
 * (which were generated by the Python reference implementation).
 *
 * Run: node frontend/js/canonical.test.js
 */

"use strict";

var assert = require("assert");
var path = require("path");
var fs = require("fs");

var canonical = require("./canonical.js");

// ── Load test vectors ──────────────────────────────────────────

var vectorsPath = path.resolve(__dirname, "..", "..", "contract", "test_vectors.json");
var vectorsData = JSON.parse(fs.readFileSync(vectorsPath, "utf-8"));
var vectors = vectorsData.vectors;

var passed = 0;
var failed = 0;

function ok(msg) {
    passed++;
    console.log("  PASS: " + msg);
}

function fail(msg) {
    failed++;
    console.error("  FAIL: " + msg);
}

console.log("");
console.log("=== canonical.test.js — " + vectors.length + " vectors ===");
console.log("");

// ── Test each vector ────────────────────────────────────────────

vectors.forEach(function (vector, index) {
    var desc = "vector " + index + ": " + vector.description;

    if (vector.should_raise) {
        // This vector must raise an error.
        try {
            canonical.draftHash(vector.draft);
            fail(desc + " — expected error but none was raised");
        } catch (e) {
            ok(desc + " — raised as expected (" + e.message + ")");
        }
    } else {
        try {
            var actual = canonical.draftHash(vector.draft);
            var expected = vector.expected_hash;
            assert.strictEqual(
                actual,
                expected,
                desc + " — hash mismatch"
            );
            ok(desc + " — " + actual.substring(0, 16) + "...");
        } catch (e) {
            if (e instanceof assert.AssertionError) {
                fail(desc + " — " + e.message);
            } else {
                fail(desc + " — unexpected error: " + e.message);
            }
        }
    }
});

// ── Key-order independence ─────────────────────────────────────

(function () {
    var h0 = canonical.draftHash(vectors[0].draft);
    var h1 = canonical.draftHash(vectors[1].draft);
    var h2 = canonical.draftHash(vectors[2].draft);
    try {
        assert.strictEqual(h0, h1, "key order independence (v0 vs v1)");
        assert.strictEqual(h0, h2, "key order independence (v0 vs v2)");
        ok("key-order independence: v0 == v1 == v2");
    } catch (e) {
        fail(e.message);
    }
})();

// ── Excluded fields do not affect hash ─────────────────────────

(function () {
    var hWithout = canonical.draftHash(vectors[0].draft);
    var hWith = canonical.draftHash(vectors[5].draft);
    try {
        assert.strictEqual(hWithout, hWith, "excluded fields affect hash");
        ok("excluded fields (signature, confidence) do not affect hash");
    } catch (e) {
        fail(e.message);
    }
})();

// ── One-char change produces different hash ────────────────────

(function () {
    var hOriginal = canonical.draftHash(vectors[0].draft);
    var hChanged = canonical.draftHash(vectors[7].draft);
    try {
        assert.notStrictEqual(hOriginal, hChanged, "one-char change did not change hash");
        ok("one-character change produces a different hash");
    } catch (e) {
        fail(e.message);
    }
})();

// ── Array order matters ────────────────────────────────────────

(function () {
    var h1 = canonical.draftHash(vectors[9].draft);
    var h2 = canonical.draftHash(vectors[10].draft);
    try {
        assert.notStrictEqual(h1, h2, "array order did not matter");
        ok("array element order affects hash");
    } catch (e) {
        fail(e.message);
    }
})();

// ── No whitespace between tokens in canonical bytes ────────────

(function () {
    var bytes = canonical.canonicalBytes(vectors[0].draft);
    var s = Buffer.from(bytes).toString("utf-8");
    // Spaces inside string values are fine; we only check for whitespace
    // that would appear as token separators (after { [ , : and before } ] ,).
    var structuralSpace = /[{\[,]\s|\s[}\],]|:\s|\s:/.test(s);
    try {
        assert.strictEqual(structuralSpace, false, "whitespace found between tokens");
        ok("no whitespace between tokens in canonical bytes");
    } catch (e) {
        fail(e.message);
    }
})();

// ── Non-BMP key sorting (code point, not UTF-16) ───────────────

(function () {
    // Vector 4 has an emoji key. If we were sorting by UTF-16 code units
    // instead of code points, the hash would differ. The expected hash
    // was computed with code-point sorting in Python.
    var h = canonical.draftHash(vectors[4].draft);
    try {
        assert.strictEqual(h, vectors[4].expected_hash, "non-BMP key sort mismatch");
        ok("non-BMP characters in keys sorted by code point (not UTF-16)");
    } catch (e) {
        fail(e.message);
    }
})();

// ── Determinism ────────────────────────────────────────────────

(function () {
    var b1 = canonical.canonicalBytes(vectors[0].draft);
    var b2 = canonical.canonicalBytes(vectors[0].draft);
    try {
        assert.deepStrictEqual(
            Array.from(b1),
            Array.from(b2),
            "canonical_bytes is not deterministic"
        );
        ok("canonical_bytes is deterministic");
    } catch (e) {
        fail(e.message);
    }
})();

// ── Summary ────────────────────────────────────────────────────

console.log("");
console.log("=== " + passed + " passed, " + failed + " failed ===");
console.log("");

if (failed > 0) {
    process.exit(1);
}
